### ISSUE TITLE
GC overhead limit exceeded (Error 597)

### ISSUE THREAD

**Issue by FlorianHockmann** [PommeVerte/gremlin-bin#22]
Hi,

first of all thanks for GremlinBin! It's really a great tool to try out Gremlin queries.

Unfortunately, the console hangs completely at the moment for me. Before that, I got the following error message:

> Could not complete query => GC overhead limit exceeded (Error 597)

Maybe a simple restart can already 'fix' this issue?

**Comment by dmill-bz** [comment]
Hey this should be fixed. wow never got a notification for this so I'm terribly sorry it took this long for you to get a response. Please feel free to open again if you're having issues.
