### ISSUE TITLE
Any design tools like Protege?

### ISSUE THREAD

**Issue by BPMNhero** [PommeVerte/gremlin-bin#24]
I am a new user of gremlin.
I have used gremlin console and am able to create and query small graphs. Are there any design tools that allow for larger creations that are not driven by typing every line in a text editor while providing some error checking like protege can do for OWL based databases? I am looking to support an enterprise class database and I just don't see the tools for that here. Am I looking in the wrong place?
Thanks for you time.

**Comment by dmill-bz** [comment]
Hey,

This would be better asked on the gremlin-user mailing list : https://groups.google.com/forum/#!forum/gremlin-users

You might want to have a look at http://tinkerpop.apache.org/docs/current/reference/#gephi-plugin or eventually at DSE graph as they may provide some tools (not sure there) :) 

If you ever find an answer and have the time to keep me updated that would be great.
