### ISSUE TITLE
Your demo is broken

### ISSUE THREAD

**Issue by ftrotter** [PommeVerte/gremlin-bin#25]
I get:
Error: Your initializing script produced an error : 
Error: No signature of method: org.codehaus.groovy.ast.ClassNode.getMethod() is applicable for argument types: (java.lang.String) values: [checkOnMethodStart]
Possible solutions: getAt(java.lang.String) (Error 500)

Or something like when I try to start a graph.

**Comment by qingdo** [comment]
I got the same problem too...

**Comment by mas-dse-nbudhath** [comment]
Same Error. Is this error fixed yet?

**Comment by dmill-bz** [comment]
Sorry it took so long to get back to this. I was on trip with very limited internet access. This should be fixed. I'm running some more tests to see if it's ok. 

As an FYI the provider for the servers had a global issue and a lot of their hardware required resetting. The timing is too close for this to just be a coincidence. I'm assuming something went wrong during the booting procedure.
