### ISSUE TITLE
ERROR loading graph

### ISSUE THREAD

**Issue by mas-dse-nbudhath** [PommeVerte/gremlin-bin#26]
Error: Your initializing script produced an error : 
Error: No signature of method: org.codehaus.groovy.ast.ClassNode.getMethod() is applicable for argument types: (java.lang.String) values: [checkOnMethodStart]
Possible solutions: getAt(java.lang.String) (Error 500)

I get this every time I try to load graph.

**Comment by dmill-bz** [comment]
this should be fixed.
