### ISSUE TITLE
Website redirects to spam

### ISSUE THREAD

**Issue by kainswor** [PommeVerte/gremlin-bin#29]
Title says it all. Are there plans to continue hosting this, otherwise, it would be interesting to know what else went into it, beyond your node project for visualization

Thanks

**Comment by dmill-bz** [comment]
This project was put on hold a while ago.  I have had a bit more time as of late but if I ever revive this it will be done only using parts of this project and will be fully open source.

I will update the readme to reflect the current status of the project.
